### ISSUE TITLE
Allow toolbar config via options

### ISSUE THREAD

**Issue by runeb** [sanity-io/sanity-plugin-markdown#1]
As of version `2.0.0` we hard-code the available styles and Toolbar options

https://github.com/sanity-io/sanity-plugin-markdown/blob/1be75013d8614d3d9ce91729f98f870bf8afb289/src/components/Editor.jsx#L57-L61

It would be relatively trivial to make these configurable via options to the field, something like

```javascript
{
  name: "body",
  type: "markdown",
  options: {
    toolbarCommands: [
      ['header', 'bold', 'italic', 'strikethrough'], 
      ['link', 'quote', 'code'], 
      ['unordered-list', 'ordered-list', 'checked-list'], 
    ]
  }
}
```

**Comment by KittyGiraudel** [comment]
Hello @runeb. Are you planning on releasing this on npm? :)

**Comment by Hahlh** [comment]
@KittyGiraudel It looks like this is already usable. I am not sure whether it has been released in the meantime and you already know, but I thought that a ping wouldn't hurt.
