### ISSUE TITLE
Trouble installing with `sanity install` (Unknown type: markdown)

### ISSUE THREAD

**Issue by ctjlewis** [sanity-io/sanity-plugin-markdown#10]
`sanity install markdown` not working as expected:

```none
 Valid types are: settings, post, author, category, blockContent, comment, array, block, boolean, datetime, date, document, email, file, geopoint, image, number, object, reference, slug, string, telephone, text and url
```

**Comment by ctjlewis** [comment]
Tried working around with:

`yarn add sanity-plugin-markdown`

and:

`yarn sanity install`

Since Sanity appeared to just be trying to install from `package.json`, but that also did not work. It is genuinely incredible how obnoxious JS tooling is to the point where even installing something is an absolute nightmare.

**Comment by ctjlewis** [comment]
This appears to be an issue with Sanity itself, closing this:

https://github.com/sanity-io/sanity-plugin-markdown/issues/10

**Comment by toiq** [comment]
@ctjlewis any solution?

**Comment by ctjlewis** [comment]
This project had a `studio/` directory containing the Sanity  install, which needed to be the working directory for the install to work, rather than the root directory.

**Comment by eneskutlay** [comment]
Are you sure you are running the command inside the **root file of Sanity?** Maybe you are running it in the _root file of the project._ Cause I made the same mistake 😇

**Comment by iliawm** [comment]
just npm install sanity-plugin-markdown
then go to your your sanity.config.ts:  and import {markdownSchema} from 'sanity-plugin-markdown' after that use markdownSchema() within plugin section like   plugins: [

      markdownSchema()
  ],
}) in the same page u imported it
