### ISSUE TITLE
Some special characters doesnt work in markdown?

### ISSUE THREAD

**Issue by thebosph** [sanity-io/sanity-plugin-markdown#20]
Hello everyone i have a problem. I am building a blog site nextjs + sanity.io. I installed sanity-plugin-markdown but math formulas doesn't work. How can i use math formulas ? Thank
![Ekran Resmi 2021-11-08 21 33 33](https://user-images.githubusercontent.com/82698375/140798274-c3e9e9fe-8650-4516-8dd2-c269100a381e.png)
s.
![Ekran Resmi 2021-11-08 21 33 46](https://user-images.githubusercontent.com/82698375/140798323-bb3a8687-4aa5-4be9-be4c-8a190daa311e.png)

**Comment by kmelve** [comment]
Hi! This plugin uses [Github Flavored Markdown](https://github.github.com/gfm/), which doesn't support math equations out of the box. 

You could also explore using the [built-in block content editor](https://www.sanity.io/docs/block-content) and [the LaTeX plugin](https://www.sanity.io/plugins/sanity-plugin-latex-input) which lets you insert math equations as their own blocks.

**Comment by thebosph** [comment]
Thanks a lot!
