### ISSUE TITLE
Drag to upload and formatting buttons not working

### ISSUE THREAD

**Issue by jakio** [sanity-io/sanity-plugin-markdown#21]
Installing the latest version of sanity-plugin-markdown on a clean Sanity project - seems to result in slightly broken markdown editor. Text editing and Preview button works but in-line images, drag images and formatting buttons do not.

**Comment by Anthropic** [comment]
@runeb I am having the same issue, our admin have broken with a recent Sanity update where we use this plugin.

**Comment by shamalainen** [comment]
@jakio @Anthropic Noticed the same issue. Reverted to @2.0.4 and everything seems to be working.

**Comment by estrattonbailey** [comment]
Same issue, on `@sanity/core@2.22.3`. Getting this error in console for both formatting buttons and image uploads (all methods of inserting images).

<img width="571" alt="Screen Shot 2021-12-16 at 3 43 19 PM" src="https://user-images.githubusercontent.com/4732330/146455855-7c80bc2c-1b58-480f-88f8-d408ca16b83c.png">

And when uploading images, I get this little flash noty.

<img width="440" alt="Screen Shot 2021-12-16 at 3 43 30 PM" src="https://user-images.githubusercontent.com/4732330/146455880-a79266a2-d550-4bf3-be03-4cbb48b3b186.png">

I downgraded to 2.0.4 (I had previously [had issues with this version](https://github.com/sanity-io/sanity-plugin-markdown/issues/13#issuecomment-943673287) in #13) and it works, however I still get that flash notification. So it says it failed, but it seems to work.

**Comment by runeb** [comment]
Thanks for reporting this, we are looking into it

**Comment by robinpyon** [comment]
This should now be resolved in `2.1.1` – please do shout if if the issue persists!
