### ISSUE TITLE
Viewer role editor can edit markdown input

### ISSUE THREAD

**Issue by rxkevin** [sanity-io/sanity-plugin-markdown#22]
In Viewer role mode, markdown input still allows the viewer to edit.

<img width="808" alt="Screenshot 2021-12-08 at 10 38 39" src="https://user-images.githubusercontent.com/72786689/145177136-ecc65198-2050-4c4a-be61-39fa7f0ddd76.png">

**Comment by runeb** [comment]
@rxkevin I am aware that the input does not look disabled when in readOnly mode. Is it accepting text input? If so, what feedback do you get after text is input?

**Comment by robinpyon** [comment]
Thanks for reporting @rxkevin

This was a visual bug (the input would still be disabled despite looking active) and has since been fixed in `2.1.1`.
