### ISSUE TITLE
V3 deploy issue with developer preview 13 and later

### ISSUE THREAD

**Issue by ottob** [sanity-io/sanity-plugin-markdown#28]
When I did a fresh yarn install I got this message:
> warning " > sanity-plugin-markdown@3.0.0-v3-studio.0" has incorrect peer dependency "sanity@dev-preview".

Running the studio with `sanity start` works. But if I try to deploy it `sanity deploy` I get this error:

```
yarn run v1.22.19
$ sanity deploy
✔ Checking project info
✔ Clean output folder (4ms)
✖ Build Sanity Studio

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/Users/myuser/dev/studio/dist/static//x00@sanity-studio-entry.f5725f7e.css'
    at writeOutputFile (file://~/dev/studio/node_modules/rollup/dist/es/shared/rollup.js:23800:34)
    at async Queue.work (file://~/dev/studio/node_modules/rollup/dist/es/shared/rollup.js:22773:32)
error Command failed with exit code 1.
```

Im running sanity 3.0.0-dev-preview.14
$ sanity --version
@sanity/cli version 3.0.0-v3-pte.17+4b7aeb686f

**Comment by ottob** [comment]
maybe @rexxars or @mariuslundgard knows why?

**Comment by rexxars** [comment]
Could you try using [v3.0.0-dev-preview.15](https://github.com/sanity-io/sanity/releases/tag/v3.0.0-dev-preview.15)? 

If you're still having issues, it would be interesting to hear if perhaps there are multiple versions of the `sanity` module installed: `npm ls sanity` or `yarn why sanity` might give an answer to that question.

**Comment by ottob** [comment]
preview.15 fixed it. Thanks!

**Comment by ottob** [comment]
Sorry, opened the Champagne too soon 😅

When I visit the deployed studio I see the studio and a loading spinner and then the top menu bar. But then I think it tries to load the content and I get a white screen of death and there is an error in the console:
react_devtools_backend.js:4026 Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.da (sanity.3090c75a.js:81:52982)
    at Tn.useMemo (sanity.3090c75a.js:12:5954)
    at TOt (sanity.3090c75a.js:1526:10465)
    at N9 (sanity.3090c75a.js?v=022adcb6:81:53252)
    at wxe (sanity.3090c75a.js?v=022adcb6:85:8857)
    at yxe (sanity.3090c75a.js?v=022adcb6:85:964)
    at Jqe (sanity.3090c75a.js?v=022adcb6:85:887)
    at r1 (sanity.3090c75a.js?v=022adcb6:85:737)
    at U4 (sanity.3090c75a.js?v=022adcb6:83:10947)
    at sanity.3090c75a.js?v=022adcb6:81:39036

<img width="1023" alt="Screenshot 2022-08-17 at 20 46 59" src="https://user-images.githubusercontent.com/67104/185218798-868cabee-7881-4b8f-a232-a9aafc0e4723.png">


yarn why studio says:

yarn why sanity
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "sanity"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "sanity@3.0.0-v3-v2-pte.56"
info Has been hoisted to "sanity"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "53.86MB"
info Disk size with unique dependencies: "185.76MB"
info Disk size with transitive dependencies: "53.86MB"
info Number of shared dependencies: 224
✨  Done in 2.60s.

**Comment by rexxars** [comment]
Hmm, it shouldn't be using `sanity@3.0.0-v3-v2-pte.56` - it should be on `dev-preview` - eg `3.0.0-dev-preview.15` - is that what is in your `package.json` file?

**Comment by ottob** [comment]
Thanks! Yeah, there was a `^` in front of the version. If I ran `yarn upgrade sanity@dev-preview` it ended up installing the correct preview.15 version, and now the deployed version works as expected. Thanks again!

**Comment by ottob** [comment]
Two steps forward, one step back. Deploying the studio worked. And browsing content in the desk that does not use markdown works. But as soon as I open content using the markdown plugin I get this error:

<img width="1223" alt="Screenshot 2022-08-19 at 21 57 51" src="https://user-images.githubusercontent.com/67104/185697645-25ae020b-e9d6-40e5-be56-14bd49979a1c.png">

**Comment by alex289** [comment]
Thats exactly my [issue](https://github.com/sanity-io/sanity/issues/3533).

**Comment by snorrees** [comment]
Thanks for the heads up! 

Released a new version that fixes the crash, but its a breaking change as we had to change the markdown editor to make it play nice with the build. 

https://github.com/sanity-io/sanity-plugin-markdown/releases/tag/v3.0.0-v3-studio.1

With this version you should have an working editor, but image upload is not working. Sorry!

**Comment by ottob** [comment]
No problem, just happy to see some progress! Im aware of the cost of living on the edge 😀

**Comment by ottob** [comment]
Im just curious, I noticed that there is a @next (12.*) version of react-mde. Perhaps that would work and let image uploads continue to work?

**Comment by snorrees** [comment]
> Im just curious, I noticed that there is a @next (12.*) version of react-mde. Perhaps that would work and let image uploads continue to work?

Browsing the issues on react-mde, I saw he author of the lib mention that there was no time to work on the lib right now. It is also a headless version, and probably has breaking changes.

I think react-md-editor can be made to support images with custom actions, its just a bit more to take on that we have bandwidth for at this exact moment. Hopefully we can ship something more complete in the weeks to come. Might decide to go back to react-mde or some other editor then too, but ATM this is the best I could offer.

**Comment by ottob** [comment]
I can confirm that the new version solved the crash for me and I can now use markdown types in my content. Thanks!
