### ISSUE TITLE
font size change in studio after installing plugin

### ISSUE THREAD

**Issue by sachinsancheti1** [sanity-io/sanity-plugin-markdown#5]
The font size of the studio (dashboard, desk etc) change when I install this plugin. I am unsure where the problem is, but as a user I found this happen.

After uninstalling the plugin, the font changes back to being the bigger font I usually have. I was earlier using version 1.0.1

**Comment by runeb** [comment]
@sachinsancheti1 Which version of this plugin did you try to install, and which Studio version? And do you have css information of the texts that changed font? I cannot reproduce in my own studio, but it could be some leaky css on a certain version combination.

**Comment by sachinsancheti1** [comment]
I am using Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)
I installed the `"sanity-plugin-markdown": "^2.0.1"`

Before Installing:
![before-1](https://user-images.githubusercontent.com/6279770/117523663-352e7a80-afd7-11eb-8d24-1fa778c59894.jpg)

After Installing:
![after-1](https://user-images.githubusercontent.com/6279770/117523670-3b245b80-afd7-11eb-9edd-d217ed1f9b36.jpg)

I went through the css from the devtools and pulled out the following information from the `Computed` tab. Here are attached the before and after computed css of the `Post` word and the svg icon above it.

[before-icon.txt](https://github.com/sanity-io/sanity-plugin-markdown/files/6445073/before-icon.txt)
[before-post.txt](https://github.com/sanity-io/sanity-plugin-markdown/files/6445074/before-post.txt)
[after-icon.txt](https://github.com/sanity-io/sanity-plugin-markdown/files/6445075/after-icon.txt)
[after-post.txt](https://github.com/sanity-io/sanity-plugin-markdown/files/6445077/after-post.txt)

My feeling is there is something to do with `em` calculation and the `line-height` css leaking.

**Comment by sachinsancheti1** [comment]
Dear @runeb ,

I found it. the file `/src/components/Editor.css` directly injects this into the dashboard.
![image](https://user-images.githubusercontent.com/6279770/117524479-07e3cb80-afdb-11eb-87c9-7d2a662269c9.png)
